# services:
#   app-dis:
#     image: test_dis
#     container_name: app
#     restart: always   
#     working_dir: /app
#     volumes:
#      - /home/arunkumar/commonfs:/app/commonfs
#     ports:
#       - "5001:5001"
#     environment:
#       NODE_ENV: production
#     command: node index.js
#     build:
#       context: .
#       dockerfile: Dockerfile

version: '3.8'
services:
  app:
    build: .
    ports:
      - "5001:5001"
    volumes:
      - .:/app
      - /app/node_modules
      - /home/arunkumar/commonfs:/app/commonfs

